name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js enviornment
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install
        
      - name: Build
        run: yarn build
        
      - name: Upload Artifacts
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ieee.icet.ac.in
          username: subiee
          password: ${{ secrets.ftp_password }}
          local-dir: ./build/
          dangerous-clean-slate: true
